apiVersion: apps/v1
kind: Deployment
metadata:
  name: n3n-ai
  namespace: n3n-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n3n-ai
  template:
    metadata:
      labels:
        app: n3n-ai
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: n3n-ai
          image: ghcr.io/n3n-dev/n3n-ai:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: n3n-ai-svc
  namespace: n3n-ai
spec:
  selector:
    app: n3n-ai
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n3n-ai-ingress
  namespace: n3n-ai
spec:
  ingressClassName: traefik
  rules:
    - host: n3n-ai-dev.d2.nthreen.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: n3n-ai-svc
                port:
                  number: 80
